### PR TITLE
Remove system cmake from all spack templates

### PR DESCRIPTION
**Pull request by xylar**
Trilinos needs a newer cmake than is available on any system so we will let spack build cmake.

This merge also removes files associated with some old machines.

### CODE REVIEW

**Comment by xylar** [comment]
@trhille, please let me know how this goes on Chicoma.  We'll test other machines as needed.

**Comment by trhille** [comment]
@xylar, I'm testing this on `compass/main` with:
```
$export CONDA_BASE=${HOME}/mambaforge
export TMPDIR=/lustre/scratch4/turquoise/.mdt1/trhille/spack_temp
./conda/configure_compass_env.py --conda ${CONDA_BASE} \
--mache_fork xylar/mache --mache_branch  update_cmake_for_albany \
--update_spack --spack /lustre/scratch4/turquoise/.mdt1/trhille/spack_test \
--tmpdir ${TMPDIR} --compiler gnu --mpi mpich --recreate --with_albany
```
I'll follow up with results later, as this will likely take several hours to run.

**Comment by xylar** [comment]
🤞🏻

**Comment by trhille** [comment]
@xylar, I'm still getting the same error:
```
1 error found in build log:
  >> 5    CMake Error at CMakeLists.txt:62 (CMAKE_MINIMUM_REQUIRED):
     6      CMake 3.23.0 or higher is required.  You are running version 3.20.3
     7    
     8    
     9    -- Configuring incomplete, errors occurred!

See build log for details:
  /lustre/scratch4/turquoise/.mdt1/trhille/spack_temp/spack-stage/spack-stage-trilinos-for-albany-develop-jkvnaiv3aovrxaaoexun7nndsz7bvjcb/spack-build-out.txt

==> Warning: Skipping build of albany-develop-mrq6dnnp2dqwptb2rhnty4veov32try4 since trilinos-for-albany-develop-jkvnaiv3aovrxaaoexun7nndsz7bvjcb failed
==> Error: albany-develop-mrq6dnnp2dqwptb2rhnty4veov32try4: Package was not installed
```

**Comment by xylar** [comment]
@trhille, can you look at what version of CMake Spack installed?

**Comment by trhille** [comment]
I'm seeing this:
```
==> Concretized cmake
[+]  3iaiqic  cmake@3.20.3%gcc@12.1.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-sles15-zen2
```

**Comment by xylar** [comment]
I don't understand why it's defaulting to such an old version when there is a much newer one available:
https://github.com/E3SM-Project/spack/blob/develop/var/spack/repos/builtin/packages/cmake/package.py#L31
Could you share the dev*.yaml file in `conda/build_*`?  That might give us a clue if there's something other than just `cmake` being specified by mistake somehow.

**Comment by xylar** [comment]
What happens if you manually add a specific version after the cmake spec in the `dev*.yaml`:
```
cmake@3.24.3
```
and then run 
```
/bin/bash build_*.sh
```
(probably fill in the full names of the files for `*`, I just don't recall the details.)

**Comment by xylar** [comment]
BTW, I can take over testing this tomorrow.  I just don't have the energy tonight.

**Comment by xylar** [comment]
@ikalash, do you have any thoughts?  Did Trilinos just ratchet up the required CMake version to something newer than we have installed anywhere?  Is your nightly testing still working okay?

**Comment by trhille** [comment]
> I don't understand why it's defaulting to such an old version when there is a much newer one available: https://github.com/E3SM-Project/spack/blob/develop/var/spack/repos/builtin/packages/cmake/package.py#L31 Could you share the dev*.yaml file in `conda/build_*`? That might give us a clue if there's something other than just `cmake` being specified by mistake somehow.

This is the only place where `cmake` is used in that file:
```
spack:
  specs:
  - cmake
  - gcc
  - mpich

  - cray-libsci


  - hdf5
  - netcdf-c
  - netcdf-fortran
  - parallel-netcdf

  - esmf@8.2.0+mpi+netcdf~pio+pnetcdf
  - scorpio@1.3.2+pnetcdf~timing+internal-timing~tools+malloc
  - albany@develop+mpas
```

**Comment by trhille** [comment]
> What happens if you manually add a specific version after the cmake spec in the `dev*.yaml`:
> 
> ```
> cmake@3.24.3
> ```
> 
> and then run
> 
> ```
> /bin/bash build_*.sh
> ```
> 
> (probably fill in the full names of the files for `*`, I just don't recall the details.)

testing now

**Comment by xylar** [comment]
@trhille, if that works, we can hard-code a cmake version on the compass side.

I think the reason it didn't build its own CMake version without encouragement is that the system CMake it has previously included was still compatible with the specification provided.

**Pull request merged**
