### PR TITLE
Update to 1.24.0

### PR DESCRIPTION
**Pull request by altheaden**
This PR updates the version number for mache in three files: `conda/meta.yaml`, `version.py`, and `setup.cfg`.

Checklist
* [ ] `Testing` comment in the PR documents testing used to verify the changes

### CODE REVIEW

**Comment by altheaden** [comment]
@xylar I created this off of the current main, but if you would like to wait until after #175 goes through, I can easily rebase it after that's merged.

**Comment by xylar** [comment]
Let's wait on this for now and rebase onto `main` once #175 goes in.  Could you put the new version number in the title of the PR explicitly?  That will make it a little easier to identify later.

**Comment by xylar** [comment]
This looks good.  The conflict is pretty obvious (we deleted `setup.cfg` in #175) so hopefully it's easy to fix as part of a rebase.

**Comment by xylar** [comment]
@altheaden, it looks like we have some fixing to do in CI.  It would be a little cleaner to do that in a new PR. See:
https://github.com/search?q=repo%3AE3SM-Project%2Fmache%20setup.cfg&type=code

**Comment by xylar** [comment]
These need to be changed from `setup.cfg` to either `pyproject.toml` or `.flake8`.  Hopefully, it's obvious which is which but if not, just ask.

**Comment by altheaden** [comment]
Yep, I just noticed that as well. I can make a separate PR for that.

**Review by xylar — APPROVED** [review]

**Pull request merged**
