### PR TITLE
Add `chicoma-gpu`

### LINKED ISSUE #180: Add chicoma-gpu
Following pm-gpu, we want to add files to support chicoma-gpu.

### PR DESCRIPTION
**Pull request by altheaden**
In this PR I added the necessary files to add `chicoma-gpu` to mache. The files for the `nvidia` and `gnu` compilers are symlinks to the existing `chicoma-cpu` files, while the `nvidiagpu` and `gnugpu` files are newly created. 

Checklist
* [ ] `Testing` comment in the PR documents testing used to verify the changes

closes #180

### CODE REVIEW

**Comment by altheaden** [comment]
@xylar will do testing on chicoma since I do not have access. It's likely that some changes still need to be done to the `nvidiagpu` and `gnugpu` files, but I did try to update them via what's in the `config_machines.xml` file to get things started.

**Comment by altheaden** [comment]
I realized after committing this that there is some documentation referencing the supported machines. I'll update that to include this machine as well and push that to this branch tomorrow.

**Comment by altheaden** [comment]
@xylar In regards to adding new machines to `discover.py`, do we want to add another regex to find `chicoma-gpu` from its hostname? I noticed that we don't have an entry for `pm-gpu`, so I'm unsure if we need a separate one from `chicoma-cpu`. If we do, I need to know what the hostnames look like for `chicoma-gpu`, I've looked at the documentation that I have access to but I can't find anything about it.

**Comment by xylar** [comment]
@altheaden, no we can't do that because chicoma-cpu and chicoma-gpu (just as pm-cpu and pm-gpu) have the same login nodes so the hostname at least on the login nodes can't tell us which is which.  We default to the `-cpu` version and make the user specify if they want the `-gpu` version.

**Comment by xylar** [comment]
Thanks for asking, though!

**Comment by altheaden** [comment]
@xylar thanks! I realized that the documentation was referring to hostnames, so nothing needs to be updated for this PR after all, and my work here is done as far as I can tell.

**Comment by xylar** [comment]
@altheaden, I'm going to put this on hold until I get #188 working (hopefully not too long) since those changes will also apply here.

**Comment by xylar** [comment]
This isn't a high priority for now.

**Pull request closed without merging**
